"""empty message

Revision ID: ec91d7197bb4
Revises: 13e48401bb87
Create Date: 2019-02-02 22:13:46.174092

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = 'ec91d7197bb4'
down_revision = '13e48401bb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('location', Geometry(geometry_type='POINT'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'location')
    # ### end Alembic commands ###
